
DROP TABLE IF EXISTS `portfolio`;
CREATE TABLE `portfolio` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255),
	`thumbnail` VARCHAR(255),
	`body` TEXT,
	`categories` VARCHAR(2040),
	`date_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`date_posted` TIMESTAMP NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`)
);