CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	username VARCHAR(64) NOT NULL,
	password VARCHAR(32) NOT NULL,
	email VARCHAR(64) NOT NULL,
	CONSTRAINT pk_id PRIMARY KEY (id)
);